### ISSUE TITLE
Can't load stream

### ISSUE THREAD

**Issue by Krusty27** [LucCADORET/comeover#1]
Hi, I love this project and I think it's very useful. 
Recently though, I am not able to stream any kind of video from the site, this is what a visitor gets:
![image](https://user-images.githubusercontent.com/28927643/112333954-55baa380-8cbb-11eb-8088-089956837d8c.png)

I checked and none of this problems could happen in my situation, is this a host problem or mine? 
Thank you

**Comment by LucCADORET** [comment]
Hey. Thanks for the notice. I have to check the server that connects the P2P users, it's probably the issue. Don't hesitate to ping me again if the problem is not solved.

**Comment by igorcmelo** [comment]
> Hey. Thanks for the notice. I have to check the server that connects the P2P users, it's probably the issue. Don't hesitate to ping me again if the problem is not solved.

Hello, @LucCADORET, I am having the same problem here.
The progress show 0 B / 0 B.

Also the messages just doesn't appear.

**Comment by LucCADORET** [comment]
It's fixed, it should work now. Sorry for the delay. Enjoy !

**Comment by igorcmelo** [comment]
> It's fixed, it should work now. Sorry for the delay. Enjoy !

Thanks! This project is awesome :)

**Comment by Krusty27** [comment]
Thank you for your work :)
I'm sorry but it still happens to me on mobile [Android, Brave and Firefox] is there something I can do to fix?
